name: HEW
favicon: null
layout_spectrum: 0.99458
typography_spectrum: 0.56482
title: Hagelandse ElektriciteitsWerken
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71515909-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e9eab1'
    - '#aeaf84'
    - '#69695d'
    - '#3a3a2c'
  brandStrength: 0.7002332510892302
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
