title: Hagelandse ElektriciteitsWerken
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7319149
  brandStrength: 0.7808511
  lightness: 0.812766
  brandColors:
    - '#4A4B5C'
    - '#BEAB87'
    - '#1F1E42'
    - '#FBF1B4'
    - '#7FBBB4'
  rhythmicContrast: 0.6255319
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-71515909-1
  facebook: null
favicon: null
name: HEW
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.56482
layout_spectrum: 0.99458
